/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Registry {
  /** 逐条后处理文档（默认值 → 同步 fn → 递归下钻 → 权限裁剪），返回 `{doc}` */
  processNode(gql: string, doc: any, ctx?: any | undefined | null): any
  /** 需由 Host 异步执行的计算列 `fnRef` 列表（已按 `comp.read` 权限过滤） */
  asyncFnRefs(model: string, ctx?: any | undefined | null): Array<string>
  /** 收集关系依赖并注入 AST，返回 `{relDeps, ast, injectInfo}` */
  injectDepends(gql: string): any
  /** 剥离 asyncFn 依赖注入的字段，返回 `{items}` */
  stripDepInjected(injectInfo: any, items: Array<any>): any
  /** finalize 第一阶段：逐条 `process_node`，返回 `{items, fnRefs}` */
  prepareQuery(postprocess: any, items: Array<any>, ctx?: any | undefined | null): any
  /** finalize 第三阶段：剥离 asyncFn 依赖注入的字段，返回 `{items}` */
  stripQuery(postprocess: any, items: Array<any>): any
  /**
   * 解析 schema 绑定的数据源 kind（`"mongo"` / `"mysql"` / `"postgres"` / `"sqlite"`）
   *
   * `config` 形状：`{ "sources": { "<name>": "<kind>" } }`；`null` → 单源 Mongo。
   */
  resolveDatasource(schemaName: string, config?: any | undefined | null): string
  /** schema 声明的数据源名（未声明 → `null`，语义为 `default`） */
  schemaDatasource(schemaName: string): string | null
  /** 把一条 Mongo 命令 JSON 翻译为指定后端的 SQL 语句序列（见 `translate::translate`）。 */
  dialectTranslate(backend: string, cmd: any): any
  /** 把 `{rowShape, rows}` 还原为嵌套 Mongo 文档数组（平铺 JOIN 行 → 文档） */
  restoreRows(shape: any, rows: any): any
  /** 把 introspection 行 JSON → schemaJSON（`{rows}` 内含 tables/columns/fks/indexes） */
  schemaFromRows(rows: any, backend: string): any
  /** 合并 introspected 基础 schema 与本地 overlay（权限 / 计算列 / 覆盖） */
  mergeSchema(base: any, overlay: any): any
  /**
   * 生成联邦计划：按 `Schema.datasource` 把一条 GQL 拆成
   * 「各源命令序列 + 内存 join 边」；Host 逐源执行命令后调 `mergeFederated`
   *
   * 返回 `{v, kind:"federated", root, sources, join, postprocess, degraded}`；
   * 单源（无跨源关系）时 `sources` 仅根单元、`join.edges` 为空。
   */
  planFederated(gql: string, params: any, ctx?: any | undefined | null): any
  /** 合并各源结果 → 嵌套文档数组；`results` 必须与 `plan.sources` **同序同长** */
  mergeFederated(plan: any, results: Array<any>): any
  canRead(model: string, ctx?: any | undefined | null): boolean
  canWrite(model: string, ctx?: any | undefined | null): boolean
  shouldInjectOwner(model: string, ctx?: any | undefined | null): boolean
  /** 非 admin 用户只看自己数据时叠加 owner 条件；无上下文时原样返回 */
  mergeOwnerCondition(model: string, ctx?: any | undefined | null, condition?: any | undefined | null): any
  readableFields(model: string, ctx?: any | undefined | null): any
  readableRelations(model: string, ctx?: any | undefined | null): any
  writableFields(model: string, ctx?: any | undefined | null): any
  filterWritableData(model: string, ctx: any | undefined | null, data: any): any
  /** 解析 GQL 并构建 pipeline / projection，返回 `{tokens, ast, pipeline, projection}` */
  buildPipeline(gql: string, params: any, ctx?: any | undefined | null): any
  planQuery(gql: string, params: any, ctx?: any | undefined | null): any
  /** 列表 + total；`total` 由 Host 执行 `countCommand` 后回喂，用于算 `hasMore` */
  planQueryWithCount(gql: string, params: any, ctx?: any | undefined | null, total?: number | undefined | null): any
  resolvePage(gql: string, params: any): any
  /** 两阶段查询后按阶段一 `_id` 顺序重排，返回 `{items}` */
  restoreSortOrder(items: Array<any>, ids: Array<any>, sort?: any | undefined | null): any
  /** 生成插入命令；`now` / `newId` 由 Host 提供（core 无时钟与随机源） */
  planInsert(model: string, data: any, now: number, newId: string, ctx?: any | undefined | null): any
  planExists(model: string, condition: any): any
  planCount(model: string, filter?: any | undefined | null): any
  planAggregate(model: string, pipeline: Array<any>): any
  /** 批量插入命令；`newIds` 按需消费（仅无 `_id` 的文档取用） */
  planInsertMany(model: string, docs: Array<any>, now: number, newIds: Array<string>, ctx?: any | undefined | null): any
  /**
   * 更新一条（findOneAndUpdate + returnDocument AFTER）。
   *
   * creator 写权限需探针时返回 `{"needsProbe": cmd}`；Host 执行探针后携
   * `probeFound`（true/false）与 `probeDoc` 重入即得 `{"command": cmd}`。
   */
  planUpdate(model: string, condition: any, data: any, options: any | undefined | null, now: number, ctx?: any | undefined | null, probeFound?: boolean | undefined | null, probeDoc?: any | undefined | null): any
  /** 批量更新（guest / 无写授权直接拒绝，不走 creator 探针） */
  planUpdateMany(model: string, condition: any, data: any, now: number, ctx?: any | undefined | null): any
  /**
   * 删除计划：归档表存在时返回 findCommand（Host 取源文档后调 planArchiveDocs）+
   * deleteCommand。creator 探针语义同 planUpdate。
   */
  planRemove(model: string, condition: any, ctx?: any | undefined | null, probeFound?: boolean | undefined | null, probeDoc?: any | undefined | null): any
  /** 归档文档命令：源文档补 `deletedAt` 后批量写入 `<collection>_deleted` */
  planArchiveDocs(model: string, docs: Array<any>, now: number): any
  /** 显式条件 upsert；`newId` 仅在需生成 `_id` 时被使用 */
  planUpsert(model: string, condition: any, data: any, options: any | undefined | null, now: number, newId: string, ctx?: any | undefined | null): any
  /**
   * mutation 规划：展开为有序步骤序列 `{steps: [{model, command}]}`，
   * 父子依赖用 `{{step.<N>._id}}` 占位符表达，由 Host 依次执行并回填
   */
  planMutation(model: string, data: any, now: number, newIds: Array<string>, ctx?: any | undefined | null): any
  /**
   * 写路径结果回喂：对 findOneAndUpdate 返回文档补默认值 / 同步计算列
   * （对齐 JS `applyDefaultsAndComputes(result, s)`）
   */
  applyWriteDefaults(model: string, doc: any): any
  sortsByRelation(sort?: any | undefined | null): boolean
  constructor()
  /** 注册 schema（自动派生 `<Name>Deleted` 归档表；`timestamps !== false` 时补时间戳字段） */
  register(defn: any): void
  has(name: string): boolean
  list(): Array<string>
  /** 注册同步计算列回调（schema 里 `fn: true` 的 `fnRef`，缺省为计算列名） */
  setFn(fnRef: string, callback: (arg: any) => any): void
  clearFns(): void
  /** 开关用户 $pipeline 直通（默认允许；AI 查询宿主建议关闭作纵深防御） */
  setAllowUserPipeline(allow: boolean): void
}
