/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * 系统内部调用上下文工厂：`{ internal: true }` —— 权限引擎全放行、不注入 owner
 * 条件。供 Host 的内部路径（索引创建、归档回填、后台任务等）显式表达「系统调用」，
 * 与 `undefined`（未传上下文，`require_context` 开启时报错）区分。
 */
export declare function systemContext(): any
/** 命名归一（设计 §6.2）：用户任意写法 → 全小写 token 序列。 */
export declare function canonical(s: string): Array<string>
/** token 序列 → snake_case */
export declare function toSnake(tokens: Array<string>): string
/** token 序列 → camelCase */
export declare function toCamel(tokens: Array<string>): string
/** token 序列 → PascalCase */
export declare function toPascal(tokens: Array<string>): string
/** 逻辑名 → 目标风格物理名；`target` 非法 ⇒ 抛错（禁静默回落）。 */
export declare function translateName(logical: string, target: string): string
/** 命名冲突检测（A7）：一组逻辑名归一后撞名 / 撞保留键 ⇒ 抛错。 */
export declare function detectConflicts(names: Array<string>): void
/** 内容寻址路径（纯函数） */
export declare function resourceContentPath(sha1: string): string
/** 是否外部 URL（纯函数） */
export declare function resourceIsExternalUrl(reference: string): boolean
/** URL 组合（纯函数） */
export declare function resourceComposeUrl(reference: string, cfg: any): string
export declare class Registry {
  /** 逐条后处理文档（默认值 → 同步 fn → 递归下钻 → 权限裁剪），返回 `{doc}` */
  processNode(gql: string, doc: any, ctx?: any | undefined | null): any
  /** 需由 Host 异步执行的计算列 `fnRef` 列表（已按 `comp.read` 权限过滤） */
  asyncFnRefs(model: string, ctx?: any | undefined | null): Array<string>
  /** 收集关系依赖并注入 AST，返回 `{relDeps, ast, injectInfo}` */
  injectDepends(gql: string): any
  /** 剥离 asyncFn 依赖注入的字段，返回 `{items}` */
  stripDepInjected(injectInfo: any, items: Array<any>): any
  /** finalize 第一阶段：逐条 `process_node`，返回 `{items, fnRefs}` */
  prepareQuery(postprocess: any, items: Array<any>, ctx?: any | undefined | null): any
  /** finalize 第三阶段：剥离 asyncFn 依赖注入的字段，返回 `{items}` */
  stripQuery(postprocess: any, items: Array<any>): any
  /**
   * 解析 schema 绑定的数据源 kind（`"mongo"` / `"mysql"` / `"postgres"` / `"sqlite"`）
   *
   * `config` 形状：`{ "sources": { "<name>": "<kind>" } }`；`null` → 单源 Mongo。
   */
  resolveDatasource(schemaName: string, config?: any | undefined | null): string
  /** schema 声明的数据源名（未声明 → `null`，语义为 `default`） */
  schemaDatasource(schemaName: string): string | null
  /** 把一条 Mongo 命令 JSON 翻译为指定后端的 SQL 语句序列（见 `translate::translate`）。 */
  dialectTranslate(backend: string, cmd: any): any
  /** 把 `{rowShape, rows}` 还原为嵌套 Mongo 文档数组（平铺 JOIN 行 → 文档） */
  restoreRows(shape: any, rows: any): any
  /** 把 introspection 行 JSON → schemaJSON（`{rows}` 内含 tables/columns/fks/indexes） */
  schemaFromRows(rows: any, backend: string): any
  /** 合并 introspected 基础 schema 与本地 overlay（权限 / 计算列 / 覆盖） */
  mergeSchema(base: any, overlay: any): any
  /** 原生 SQL 语句编译：位置档透传 / 命名档 `:name` 编译 + 读写推断（C4；js 端 `rawStmtCompile`） */
  rawStmtCompile(backend: string, text: string, params: any, isWrite?: boolean | undefined | null): any
  /**
   * 生成联邦计划：按 schema 的 `(source, database, schema)` 与数据源 kind 把一条 GQL
   * 拆成「各源命令序列 + 内存 join 边」；Host 逐源执行命令后调 `mergeFederated`
   *
   * `dsConfig`：`{ "sources": { name: kind } }`（与 `init` 的数据源声明一致；
   * `null` = 单源 Mongo）。SQL 同源跨 database/schema 仍下推（qualified JOIN），
   * Mongo 跨 db 剥离为内存 join。
   *
   * 返回 `{v, kind:"federated", root, sources, join, postprocess, degraded, maxRowsPerSource}`；
   * 单源（无跨源关系）时 `sources` 仅根单元、`join.edges` 为空。
   */
  planFederated(gql: string, params: any, ctx?: any | undefined | null, dsConfig?: any | undefined | null): any
  /** 合并各源结果 → 嵌套文档数组；`results` 必须与 `plan.sources` **同序同长** */
  mergeFederated(plan: any, results: Array<any>): any
  /**
   * 目录语义纯规划：`store.config.json` + 目录扫描结果 → 定位后的装载项。
   *
   * `config` = `{sources, defs}`；`files` = `[{rel, defn}]`（`rel` = 相对 defs-root 的路径）。
   * 返回 `[{defn, location:{source,database,schema}}]`（主在前、其后从；组间按 name 字典序）。
   */
  planLoad(config: any, files: any): any
  /** 带定位批量注册（D13 批次唯一）；`items` = `[{defn, location}]`，`ctx` 缺省 = 无上下文。 */
  registerBatch(items: any, ctx?: any | undefined | null): void
  canRead(model: string, ctx?: any | undefined | null): boolean
  canWrite(model: string, ctx?: any | undefined | null): boolean
  shouldInjectOwner(model: string, ctx?: any | undefined | null): boolean
  /** 非 admin 用户只看自己数据时叠加 owner 条件；无上下文时原样返回 */
  mergeOwnerCondition(model: string, ctx?: any | undefined | null, condition?: any | undefined | null): any
  readableFields(model: string, ctx?: any | undefined | null): any
  readableRelations(model: string, ctx?: any | undefined | null): any
  /** 可读计算列（read 白名单判决与 fields/relations 同构；`ctx=None` → None 不裁剪） */
  readableComputes(model: string, ctx?: any | undefined | null): any
  writableFields(model: string, ctx?: any | undefined | null): any
  filterWritableData(model: string, ctx: any | undefined | null, data: any): any
  /**
   * RBAC 动作判决：`action ∈ {read, insert, update, remove}`。
   * 策略未注入 / RBAC 不介入 → true（与 plan 链路的实际拦截结果一致）。
   */
  rbacCan(model: string, action: string, ctx?: any | undefined | null): boolean
  /** RBAC 叠加后的可读字段集（静态 ∩ readFields）；`ctx=null` → null 不裁剪 */
  rbacReadableFields(model: string, ctx?: any | undefined | null): any
  /** RBAC 叠加后的可写字段集（静态 ∩ writeFields）；`ctx=null` → null 不裁剪 */
  rbacWritableFields(model: string, ctx?: any | undefined | null): any
  /**
   * RBAC 行级条件（ownerOnly / condition 的 OR 合并体）；null = 无行级收紧。
   * `action ∈ {read, update, remove}`（insert 无行级语义）。
   */
  rbacRowCondition(model: string, action: string, ctx?: any | undefined | null): any
  /**
   * 生成插入命令；`now` / `newId` 由 Host 提供（core 无时钟与随机源）
   *
   * 参数与 JS store API 一一对应（跨语言 parity 优先于参数个数），保持位置参数。
   */
  planInsert(model: string, data: any, now: number, newId: string, ctx?: any | undefined | null, routeOverride?: any | undefined | null): any
  /**
   * 批量插入命令；`newIds` 按需消费（仅无 `_id` 的文档取用）
   *
   * 参数与 JS store API 一一对应（跨语言 parity 优先于参数个数），保持位置参数。
   */
  planInsertMany(model: string, docs: Array<any>, now: number, newIds: Array<string>, ctx?: any | undefined | null, routeOverride?: any | undefined | null): any
  /**
   * 更新一条（findOneAndUpdate + returnDocument AFTER）。
   *
   * creator 写权限需探针时返回 `{"needsProbe": cmd}`；Host 执行探针后携
   * `probeFound`（true/false）与 `probeDoc` 重入即得 `{"command": cmd}`。
   *
   * 参数与 JS store API 一一对应（跨语言 parity 优先于参数个数），保持位置参数。
   */
  planUpdate(model: string, condition: any, data: any, options: any | undefined | null, now: number, ctx?: any | undefined | null, probeFound?: boolean | undefined | null, probeDoc?: any | undefined | null, routeOverride?: any | undefined | null): any
  /** 批量更新（guest / 无写授权直接拒绝，不走 creator 探针） */
  planUpdateMany(model: string, condition: any, data: any, now: number, ctx?: any | undefined | null, routeOverride?: any | undefined | null): any
  /**
   * 删除计划：归档表存在时返回 findCommand（Host 取源文档后调 planArchiveDocs）+
   * deleteCommand。creator 探针语义同 planUpdate。
   */
  planRemove(model: string, condition: any, ctx?: any | undefined | null, probeFound?: boolean | undefined | null, probeDoc?: any | undefined | null, routeOverride?: any | undefined | null): any
  /** 归档文档命令：源文档补 `deletedAt` 后批量写入 `<collection>_deleted` */
  planArchiveDocs(model: string, docs: Array<any>, now: number, routeOverride?: any | undefined | null): any
  /**
   * 显式条件 upsert；`newId` 仅在需生成 `_id` 时被使用
   *
   * 参数与 JS store API 一一对应（跨语言 parity 优先于参数个数），保持位置参数。
   */
  planUpsert(model: string, condition: any, data: any, options: any | undefined | null, now: number, newId: string, ctx?: any | undefined | null, routeOverride?: any | undefined | null): any
  /**
   * mutation 规划：展开为有序步骤序列 `{steps: [{model, command}]}`，
   * 父子依赖用 `{{step.<N>._id}}` 占位符表达，由 Host 依次执行并回填
   */
  planMutation(model: string, data: any, now: number, newIds: Array<string>, ctx?: any | undefined | null, routeOverride?: any | undefined | null): any
  /**
   * 写路径结果回喂：对 findOneAndUpdate 返回文档补默认值 / 同步计算列
   * （对齐 JS `applyDefaultsAndComputes(result, s)`）
   */
  applyWriteDefaults(model: string, doc: any): any
  /** 解析 GQL 并构建 pipeline / projection，返回 `{tokens, ast, pipeline, projection}` */
  buildPipeline(gql: string, params: any, ctx?: any | undefined | null): any
  planQuery(gql: string, params: any, ctx?: any | undefined | null, routeOverride?: any | undefined | null): any
  /** queryOne 计划：未显式 `$limit` 时强制下推 `$limit(1)` */
  planQueryOne(gql: string, params: any, ctx?: any | undefined | null, routeOverride?: any | undefined | null): any
  /** 列表 + total；`total` 由 Host 执行 `countCommand` 后回喂，用于算 `hasMore` */
  planQueryWithCount(gql: string, params: any, ctx?: any | undefined | null, total?: number | undefined | null, routeOverride?: any | undefined | null): any
  resolvePage(gql: string, params: any): any
  /** 两阶段查询后按阶段一 `_id` 顺序重排，返回 `{items}` */
  restoreSortOrder(items: Array<any>, ids: Array<any>, sort?: any | undefined | null): any
  planExists(model: string, condition: any, routeOverride?: any | undefined | null): any
  planCount(model: string, filter?: any | undefined | null, ctx?: any | undefined | null, routeOverride?: any | undefined | null): any
  sortsByRelation(sort?: any | undefined | null): boolean
  constructor()
  /** 注册 schema（自动派生 `<Name>Deleted` 归档表；`timestamps !== false` 时补时间戳字段） */
  register(defn: any): void
  has(name: string): boolean
  list(): Array<string>
  /** 清空 schema 注册表（测试隔离 / 动态重建；不动 requireContext / profile 配置开关） */
  clearSchemas(): void
  /** 注册同步计算列回调（schema 里 `fn: true` 的 `fnRef`，缺省为计算列名） */
  setFn(fnRef: string, callback: (arg: any) => any): void
  clearFns(): void
  /**
   * 开关「上下文强制」（默认关闭 = fail-open，保持 JS parity）。
   * 开启后：plan 入口遇 `ctx` 缺失抛 `ERR_NO_CONTEXT`（fail-secure），
   * 内部调用须显式传系统上下文 `systemContext()`。
   */
  setRequireContext(require: boolean): void
  /** 「上下文强制」开关当前值 */
  requireContext(): boolean
  /**
   * 设置查询档位：`"standard"`（默认，功能最大化 + 跨 DB 对齐）/
   * `"text2query"`（功能收缩 + 硬限制）。未知档位抛错（禁静默回落）。
   */
  setProfile(profile: string): void
  /** 当前查询档位字符串（`"standard"` / `"text2query"`） */
  profile(): string
  /**
   * 注入/清除 RBAC 动态策略（object 或 null）；解析失败抛错（fail-fast）。
   * 判决唯一在 core：宿主仅透传配置与查询面，plan 链路拦截自动生效。
   */
  setRbac(policy?: any | undefined | null): void
  /** RBAC 策略是否已注入 */
  rbacEnabled(): boolean
  /** 豁免角色清单（命中者在一切判决环节直接放行）。判决唯一在 core：本层零判决。 */
  setExemptRoles(roles: Array<string>): void
  /** 拒写角色清单（命中者一切写路径拒绝，读不受影响） */
  setDenyWriteRoles(roles: Array<string>): void
  /** 未配置姿态（"open" / "closed"）；未知值抛错（fail-fast，对齐 setRbac） */
  setUnconfiguredPolicy(policy: string): void
  /**
   * 定义层门禁策略（`closed=true` 时仅 internal 或 `roles` 白名单可注册/覆盖）。
   * 判决唯一在 core；默认 Open（全放行，保持既有 parity）。
   */
  setMetaPolicy(closed: boolean, roles: Array<string>): void
  /**
   * 带 ctx 的 schema 注册：定义层门禁按当前 metaPolicy 判决；`ctx` 缺省 = 无上下文。
   * 拒绝抛 `ERR_PERMISSION:` 前缀错误（定义不变）。
   */
  registerWithCtx(defn: any, ctx?: any | undefined | null): void
  /** 只读定义层判决（`workflow` 宿主面复用；判决唯一在 core）。`ctx` 缺省 = 无上下文。 */
  canRegister(ctx?: any | undefined | null): boolean
}
